export default {
    info: {
        "sp_hankuncheng": ["male", "qun", 4, ["lgs_gangrou", "lgs_yanhuan"], [], ['ext:理工杀/sp_hankuncheng.jpg', 'db:extension-理工杀:sp_hankuncheng.jpg']],
        "sp_zhuxinkun": ["male", "qun", 3, ["lgs_gangqu", "lgs_liepo", "lgs_xiushen"], [], ["zhu", 'ext:理工杀/sp_zhuxinkun.jpg', 'db:extension-理工杀:sp_zhuxinkun.jpg']],
        "sp_chenxi": ["male", "qun", 4, ["lgs_boshi", "lgs_youtu"], [], ['ext:理工杀/sp_chenxi.jpg', 'db:extension-理工杀:sp_chenxi.jpg']],
        "sp_renguanyu": ["male", "qun", "4/8", ["lgs_xinyou", "lgs_qingshen"], [], ['ext:理工杀/sp_renguanyu.jpg', 'db:extension-理工杀:sp_renguanyu.jpg']],
        "sp_wangwenxuan": ["male", "qun", 4, ["lgs_polu", "lgs_juesha"], [], ['ext:理工杀/sp_wangwenxuan.jpg', 'db:extension-理工杀:sp_wangwenxuan.jpg']],
        "sp_liutong": ["male", "qun", 4, ["lgs_tiewan"], [], ['ext:理工杀/sp_liutong.jpg', 'db:extension-理工杀:sp_liutong.jpg']],
        "sp_hankunchengzhuxinkun": ["male", "qun", 4, ["lgs_zaoxing", "lgs_qianye"], [], ['ext:理工杀/sp_hankunchengzhuxinkun.jpg', 'db:extension-理工杀:sp_hankunchengzhuxinkun.jpg']],
        "sp_chenyaoshi": ["male", "qun", 3, ["lgs_xingchi", "lgs_bushi"], [], ['ext:理工杀/sp_chenyaoshi.jpg', 'db:extension-理工杀:sp_chenyaoshi.jpg']],
        "sp_puqian": ["male", "qun", 4, ["lgs_huishi", "lgs_jiechong"], ["lgs_wangxian"], ['ext:理工杀/sp_puqian.jpg', 'db:extension-理工杀:sp_puqian.jpg']],
        "lgs_puqian": ["male", "shen", 4, ["lgs_qishi", "lgs_yange"], [], ['ext:理工杀/lgs_puqian.jpg', 'db:extension-理工杀:lgs_puqian.jpg']],
        "lgs_liutong": ["male", "shen", "4/5", ["lgs_yian", "lgs_xiaoyi"], ["lgs_yingsuo"], ['ext:理工杀/lgs_liutong.jpg', 'db:extension-理工杀:lgs_liutong.jpg']],
        "lgs_chenyaoshi": ["male", "shen", 4, ["lgs_beishan", "lgs_shenghua", "lgs_manfu"], [], ['ext:理工杀/lgs_chenyaoshi.jpg', 'db:extension-理工杀:lgs_chenyaoshi.jpg']],
        "lgs_hankuncheng": ["male", "shen", 4, ["lgs_shiyuan", "lgs_qianyin"], [], ['ext:理工杀/lgs_hankuncheng.jpg', 'db:extension-理工杀:lgs_hankuncheng.jpg', 'forbidai']],
        "lgs_chenxi": ["male", "shen", 4, ["lgs_jifei", "lgs_minghao"], [], ['ext:理工杀/lgs_chenxi.jpg', 'db:extension-理工杀:lgs_chenxi.jpg']],
        "lgs_wangwenxuan": ["male", "shen", 3, ["lgs_fengsao", "lgs_weizun"], [], ['ext:理工杀/lgs_wangwenxuan.jpg', 'db:extension-理工杀:lgs_wangwenxuan.jpg']],
        "lgs_zhuxinkun": ["male", "shen", 3, ["lgs_jieshen", "lgs_fenqu"], [], ['ext:理工杀/lgs_zhuxinkun.jpg', 'db:extension-理工杀:lgs_zhuxinkun.jpg']],
        "lgs_renguanyu": ["male", "shen", 4, ["lgs_zongyu", "lgs_nixi"], [], ['ext:理工杀/lgs_renguanyu.jpg', 'db:extension-理工杀:lgs_renguanyu.jpg']],
        "lgs_fengzichao": ["male", "shen", 3, ["lgs_jinyi", "lgs_qiujin"], [], ['ext:理工杀/lgs_fengzichao.jpg', 'db:extension-理工杀:lgs_fengzichao.jpg']],
        "lgs_wangchenhao": ["male", "shen", 3, ["lgs_daimeng", "lgs_shensuan"], [], ['ext:理工杀/lgs_wangchenhao.jpg', 'db:extension-理工杀:lgs_wangchenhao.jpg']],
        "lgs_gedongjian": ["male", "shen", 3, ["lgs_fengyu", "lgs_jianxing"], [], ['ext:理工杀/lgs_gedongjian.jpg', 'db:extension-理工杀:lgs_gedongjian.jpg']],
        "lgs_jihantao": ["male", "shen", 4, ["lgs_yonglan", "lgs_yinzhi"], [], ['ext:理工杀/lgs_jihantao.jpg', 'db:extension-理工杀:lgs_jihantao.jpg']],
        "lgs_liuyichu": ["female", "shen", 3, ["lgs_guanglan", "lgs_hairong"], [], ['ext:理工杀/lgs_liuyichu.jpg', 'db:extension-理工杀:lgs_liuyichu.jpg']],
        "lgs_wangrunshizengdiwen": ["male", "shen", 3, ["lgs_kubi"], [], ['ext:理工杀/lgs_wangrunshizengdiwen.jpg', 'db:extension-理工杀:lgs_wangrunshizengdiwen.jpg']],
        "lgs_wangzhaowen": ["female", "shen", 3, ["lgs_tianle", "lgs_jieyou"], [], ['ext:理工杀/lgs_wangzhaowen.jpg', 'db:extension-理工杀:lgs_wangzhaowen.jpg']],
        "lgs_zhangjunhao": ["male", "shen", 4, ["lgs_zhiyong", "lgs_linyi"], [], ['ext:理工杀/lgs_zhangjunhao.jpg', 'db:extension-理工杀:lgs_zhangjunhao.jpg']],
        "lgs_zhangtianyu": ["male", "shen", 4, ["lgs_miaokou"], [], ['ext:理工杀/lgs_zhangtianyu.jpg', 'db:extension-理工杀:lgs_zhangtianyu.jpg']],
        "lgs_wangyujia": ["male", "shen", 3, ["lgs_qiezhu", "lgs_woxun"], ["lgs_dingchou"], ['ext:理工杀/lgs_wangyujia.jpg', 'db:extension-理工杀:lgs_wangyujia.jpg']],
        "lgs_qijunkai": ["male", "shen", 4, ["lgs_jisun", "lgs_hongqi"], [], ['ext:理工杀/lgs_qijunkai.jpg', 'db:extension-理工杀:lgs_qijunkai.jpg']],
        "lgs_wangsiqi": ["female", "shen", 3, ["lgs_hanxiao", "lgs_chenghuan"], [], ['ext:理工杀/lgs_wangsiqi.jpg', 'db:extension-理工杀:lgs_wangsiqi.jpg']],
        "lgs_yubin": ["male", "shen", 3, ["lgs_ganggan", "lgs_xiyan"], [], ['ext:理工杀/lgs_yubin.jpg', 'db:extension-理工杀:lgs_yubin.jpg']],
        "lgs_wangyixuan": ["male", "shen", 4, ["lgs_feiqiu", "lgs_yeyin"], [], ['ext:理工杀/lgs_wangyixuan.jpg', 'db:extension-理工杀:lgs_wangyixuan.jpg']],
        "lgs_guozichen": ["male", "shen", 4, ["lgs_cangmo", "lgs_youli"], [], ['ext:理工杀/lgs_guozichen.jpg', 'db:extension-理工杀:lgs_guozichen.jpg']],
        "lgs_huxiaoyu": ["male", "shen", 3, ["lgs_shanxuan", "lgs_jieyi"], [], ['ext:理工杀/lgs_huxiaoyu.jpg', 'db:extension-理工杀:lgs_huxiaoyu.jpg']],
        "lgs_wangqi": ["male", "shen", 4, ["lgs_shannian", "lgs_jingyao"], ["lgs_fangxu"], ['ext:理工杀/lgs_wangqi.jpg', 'db:extension-理工杀:lgs_wangqi.jpg']],
        "lgs_liujingyi": ["male", "shen", 3, ["lgs_qishang"], [], ['ext:理工杀/lgs_liujingyi.jpg', 'db:extension-理工杀:lgs_liujingyi.jpg']],
        "lgs_zhangjiahui": ["female", "shen", 3, ["lgs_qiaohui", "lgs_qingwei"], ["lgs_jingjie"], ['ext:理工杀/lgs_zhangjiahui.jpg', 'db:extension-理工杀:lgs_zhangjiahui.jpg']],
        "lgs_sunqingyue": ["female", "shen", 3, ["lgs_qiaqun", "lgs_langfang"], [], ['ext:理工杀/lgs_sunqingyue.jpg', 'db:extension-理工杀:lgs_sunqingyue.jpg']],
        "lgs_pengyuhong": ["male", "shen", 4, ["lgs_chengmian", "lgs_zhiji"], [], ['ext:理工杀/lgs_pengyuhong.jpg', 'db:extension-理工杀:lgs_pengyuhong.jpg']],
        "lgs_sunjiazhi": ["male", "shen", 3, ["lgs_mengxu", "lgs_yiying"], [], ['ext:理工杀/lgs_sunjiazhi.jpg', 'db:extension-理工杀:lgs_sunjiazhi.jpg']],
        "lgs_zhouruiqi": ["male", "shen", 3, ["lgs_shuanglun", "lgs_yanta", "lgs_yingcun"], [], ['ext:理工杀/lgs_zhouruiqi.jpg', 'db:extension-理工杀:lgs_zhouruiqi.jpg']],
        "lgs_wanghongshuo": ["male", "shen", 4, ["lgs_fangyan", "lgs_ezuo", "lgs_tuqiang"], ["lgs_keji"], ['ext:理工杀/lgs_wanghongshuo.jpg', 'db:extension-理工杀:lgs_wanghongshuo.jpg']],
        "lgs_yeyueda": ["male", "shen", 4, ["lgs_xingxi", "lgs_bomie"], [], ['ext:理工杀/lgs_yeyueda.jpg', 'db:extension-理工杀:lgs_yeyueda.jpg']],
        "lgs_lixiaoting": ["female", "shen", 4, ["lgs_zhenji", "lgs_xinxing"], [], ['ext:理工杀/lgs_lixiaoting.jpg', 'db:extension-理工杀:lgs_lixiaoting.jpg']],
        "lgs_zhangliao": ["male", "wei", 4, ["lgs_tuxi", "lgs_huiwei"], ["lgs_yingzi"], ['ext:理工杀/lgs_zhangliao.jpg', 'db:extension-理工杀:lgs_zhangliao.jpg']],
        "lgs_yuxiaoran": ["female", "shen", "2/3", ["lgs_jingshu", "lgs_duyi"], [], ['ext:理工杀/lgs_yuxiaoran.jpg', 'db:extension-理工杀:lgs_yuxiaoran.jpg', 'forbidai']],
        "lgs_wanglinjing": ["female", "shen", 3, ["lgs_xiaokan", "lgs_caisi"], [], ['ext:理工杀/lgs_wanglinjing.jpg', 'db:extension-理工杀:lgs_wanglinjing.jpg', 'forbidai']],
        "lgs_liyifei": ["male", "shen", 6, ["lgs_chijiang", "lgs_huiyou"], [], ['ext:理工杀/lgs_liyifei.jpg', 'db:extension-理工杀:lgs_liyifei.jpg', 'forbidai']],
        "lgs_luyeyang": ["male", "shen", 4, ["lgs_yinwei", "lgs_shenhuai"], ["lgs_yaowu", "lgs_yangwei"], ['ext:理工杀/lgs_luyeyang.jpg', 'db:extension-理工杀:lgs_luyeyang.jpg']],
        "lgs_qujiaqi": ["female", "shen", 3, ["lgs_qjinyi", "lgs_shuangzhi"], [], ['ext:理工杀/lgs_qujiaqi.jpg', 'db:extension-理工杀:lgs_qujiaqi.jpg']],
        "lgs_qiyue": ["female", "shen", 3, ["lgs_kaizhu", "lgs_jiangxin"], [], ['ext:理工杀/lgs_qiyue.jpg', 'db:extension-理工杀:lgs_qiyue.jpg', 'forbidai']],
        "lgs_zhangliaox": ["male", "wei", 4, ["lgs_tuxix", "lgs_huiweix"], [], ['ext:理工杀/lgs_zhangliao.jpg', 'db:extension-理工杀:lgs_zhangliao.jpg', 'forbidai']],
        "lgs_guojingjun": ["female", "shen", 3, ["lgs_biluo", "lgs_qinhe"], [], ['ext:理工杀/lgs_guojingjun.jpg', 'db:extension-理工杀:lgs_guojingjun.jpg']],
        "lgs_wangjiaqi": ["female", "shen", 3, ["lgs_zhiqian", "lgs_wendao"], [], ['ext:理工杀/lgs_wangjiaqi.jpg', 'db:extension-理工杀:lgs_wangjiaqi.jpg', 'forbidai']],
        "lgs_weixinran": ["female", "shen", 3, ["lgs_liangcong", "lgs_gufang"], [], ['ext:理工杀/lgs_weixinran.jpg', 'db:extension-理工杀:lgs_weixinran.jpg']],
        "lgs_chenglinuo": ["female", "shen", 3, ["lgs_yasi", "lgs_linuo"], [], ['ext:理工杀/lgs_chenglinuo.jpg', 'db:extension-理工杀:lgs_chenglinuo.jpg']],
        "lgs_lizhaofu": ["male", "shen", 3, ["lgs_chaojie", "lgs_jueyi"], [], ['ext:理工杀/lgs_lizhaofu.jpg', 'db:extension-理工杀:lgs_lizhaofu.jpg']],
        "lgs_wangyuan": ["female", "shen", 3, ["lgs_qinmian", "lgs_yunshi"], [], ['ext:理工杀/lgs_wangyuan.jpg', 'db:extension-理工杀:lgs_wangyuan.jpg']],
        "lgs_muqing": ["female", "shen", 3, ["lgs_jiaoxin", "lgs_keyan", "lgs_renjian"], [], ['ext:理工杀/lgs_muqing.jpg', 'db:extension-理工杀:lgs_muqing.jpg', 'forbidai']],
        "lgs_wanghuan": ["female", "shen", 3, ["lgs_shouye", "lgs_ciai", "lgs_shixin"], [], ['zhu', 'ext:理工杀/lgs_wanghuan.jpg', 'db:extension-理工杀:lgs_wanghuan.jpg']],
        "sp_zengdiwen": ["male", "qun", 4, ["lgs_zhanyue", "lgs_huixie"], [], ['ext:理工杀/sp_zengdiwen.jpg', 'db:extension-理工杀:sp_zengdiwen.jpg']],
        "sp_wanghongshuo": ["male", "qun", 4, ["lgs_zhenghuo", "lgs_huahuo"], ["lgs_henhuo"], ['ext:理工杀/sp_wanghongshuo.jpg', 'db:extension-理工杀:sp_wanghongshuo.jpg', 'forbidai']],
        "sp_wangrunshi": ["male", "qun", 4, ["lgs_zhenmi", "lgs_jiehuo"], [], ['ext:理工杀/sp_wangrunshi.jpg', 'db:extension-理工杀:sp_wangrunshi.jpg']],
        "sp_wangyixuan": ["male", "qun", 4, ["lgs_touliang", "lgs_huanzhu"], [], ['ext:理工杀/sp_wangyixuan.jpg', 'db:extension-理工杀:sp_wangyixuan.jpg', 'forbidai']],
    },
    title: {
        "sp_hankuncheng": "怀勇兼柔",
        "sp_zhuxinkun": "健身达人",
        "sp_chenxi": "下晓地理",
        "sp_renguanyu": "天非吾往",
        "sp_wangwenxuan": "篮球明猩",
        "sp_liutong": "麒麟臂",
        "sp_hankunchengzhuxinkun": "黑白双坤",
        "sp_chenyaoshi": "香香",
        "sp_puqian": "预言家",
        "lgs_puqian": "哈士谦",
        "lgs_liutong": "易平义士",
        "lgs_chenyaoshi": "满腹经纶",
        "lgs_chenxi": "博古通今",
        "lgs_wangwenxuan": "猩宝",
        "lgs_hankuncheng": "成略怀德",
        "lgs_zhuxinkun": "正则律己",
        "lgs_renguanyu": "软骨鱼",
        "lgs_fengzichao": "求佛问道",
        "lgs_wangchenhao": "神算子",
        "lgs_gedongjian": "二蛋",
        "lgs_jihantao": "散神洞世",
        "lgs_liuyichu": "万卷于怀",
        "lgs_wangrunshizengdiwen": "天骄双宝",
        "lgs_wangzhaowen": "国宝",
        "lgs_zhangjunhao": "勇闯天涯",
        "lgs_zhangtianyu": "妙语连珠",
        "lgs_wangyujia": "前路漫漫",
        "lgs_qijunkai": "快意千里",
        "lgs_wangsiqi": "菡萏含苞",
        "lgs_yubin": "怕剃头",
        "lgs_wangyixuan": "夜的使者",
        "lgs_guozichen": "胸藏五学",
        "lgs_huxiaoyu": "璀璨烟火",
        "lgs_wangqi": "仁者情圣",
        "lgs_liujingyi": "尚美崇真",
        "lgs_zhangjiahui": "秀外慧中",
        "lgs_sunqingyue": "初降之露",
        "lgs_pengyuhong": "考拉",
        "lgs_sunjiazhi": "午梦初回",
        "lgs_zhouruiqi": "海阔凭鱼跃",
        "lgs_wanghongshuo": "活力胖子",
        "lgs_yeyueda": "世尘笑淡",
        "lgs_zhangliao": "威震逍遥",
        "lgs_zhangliaox": "威震逍遥",
        "lgs_yuxiaoran": "静女其姝",
        "lgs_lixiaoting": "闲庭信步",
        "lgs_wanglinjing": "指笑世艰",
        "lgs_liyifei": "诚以待人",
        "lgs_luyeyang": "板砖",
        "lgs_qujiaqi": "青青子衿",
        "lgs_qiyue": "朗日清风",
        "lgs_guojingjun": "挥毫落纸",
        "lgs_wangjiaqi": "譬如朝露",
        "lgs_weixinran": "清水芙蓉",
        "lgs_chenglinuo": "清奇瑰巧",
        "lgs_lizhaofu": "扁甫",
        "lgs_wangyuan": "文质彬彬",
        "lgs_muqing": "恪业秉初",
        "lgs_wanghuan": "师者仁心",
        "sp_zengdiwen": "骐骥一跃",
        "sp_wangrunshi": "石der",
        "sp_wanghongshuo": "大师",
        "sp_wangyixuan": "黑哥",
    },
    intro: {

    },
    sort: {
        ligongsha: {
            st316sha: ['lgs_puqian', 'lgs_liutong', 'lgs_chenyaoshi', 'lgs_chenxi', 'lgs_hankuncheng', 'lgs_wangwenxuan', 'lgs_zhuxinkun', 'lgs_renguanyu'],
            sp316sha: ['sp_hankuncheng', 'sp_zhuxinkun', 'sp_chenxi', 'sp_renguanyu', 'sp_wangwenxuan', 'sp_liutong', 'sp_puqian', 'sp_chenyaoshi', 'sp_hankunchengzhuxinkun'],
            stligongsha: ['lgs_fengzichao', 'lgs_wangchenhao', 'lgs_gedongjian', 'lgs_jihantao', 'lgs_liuyichu',
                'lgs_wangrunshizengdiwen', 'lgs_wangzhaowen', 'lgs_zhangjunhao', 'lgs_zhangtianyu',
                'lgs_wangyujia', 'lgs_qijunkai', 'lgs_wangsiqi', 'lgs_yubin', 'lgs_wangyixuan', 'lgs_guozichen',
                'lgs_huxiaoyu', 'lgs_wangqi', 'lgs_liujingyi', 'lgs_zhangjiahui', 'lgs_sunqingyue', 'lgs_pengyuhong',
                'lgs_sunjiazhi', 'lgs_zhouruiqi', 'lgs_wanghongshuo', 'lgs_yeyueda', 'lgs_lixiaoting', 'lgs_yuxiaoran',
                'lgs_wanglinjing', 'lgs_liyifei', 'lgs_luyeyang', 'lgs_qujiaqi', 'lgs_qiyue', 'lgs_guojingjun',
                'lgs_wangjiaqi', 'lgs_weixinran', 'lgs_chenglinuo', 'lgs_lizhaofu', 'lgs_wangyuan', 'lgs_muqing', 'lgs_wanghuan'],
            spligongsha: ['sp_zengdiwen', 'sp_wanghongshuo', 'sp_wangrunshi', 'sp_wangyixuan']
        },
    },
    replacement: {
        lgs_liutong: ['lgs_liutong', 'sp_liutong'],
        sp_liutong: ['sp_liutong', 'lgs_liutong'],
        lgs_chenyaoshi: ['lgs_chenyaoshi', 'sp_chenyaoshi'],
        sp_chenyaoshi: ['sp_chenyaoshi', 'lgs_chenyaoshi'],
        lgs_chenxi: ['lgs_chenxi', 'sp_chenxi'],
        sp_chenxi: ['sp_chenxi', 'lgs_chenxi'],
        lgs_hankuncheng: ['lgs_hankuncheng', 'sp_hankuncheng'],
        sp_hankuncheng: ['sp_hankuncheng', 'lgs_hankuncheng'],
        lgs_wangwenxuan: ['lgs_wangwenxuan', 'sp_wangwenxuan'],
        sp_wangwenxuan: ['sp_wangwenxuan', 'lgs_wangwenxuan'],
        lgs_puqian: ['lgs_puqian', 'sp_puqian'],
        sp_puqian: ['sp_puqian', 'lgs_puqian'],
        lgs_zhuxinkun: ['lgs_zhuxinkun', 'sp_zhuxinkun'],
        sp_zhuxinkun: ['sp_zhuxinkun', 'lgs_zhuxinkun'],
        lgs_renguanyu: ['lgs_renguanyu', 'sp_renguanyu'],
        sp_renguanyu: ['sp_renguanyu', 'lgs_renguanyu'],
        lgs_wanghongshuo: ['lgs_wanghongshuo', 'sp_wanghongshuo'],
        sp_wanghongshuo: ['sp_wanghongshuo', 'lgs_wanghongshuo'],
        lgs_wangyixuan: ['lgs_wangyixuan', 'lgs_wangyixuan'],
        sp_wangyixuan: ['sp_wangyixuan', 'lgs_wangyixuan'],
    },
    pair: {
        sp_hankuncheng: ['sp_zhuxinkun', 'sp_chenxi', 'sp_renguanyu', 'sp_wangwenxuan', 'sp_liutong', 'sp_chenyaoshi'],
        sp_zhuxinkun: ['sp_hankuncheng', 'sp_chenxi', 'sp_renguanyu', 'sp_wangwenxuan', 'sp_liutong', 'sp_chenyaoshi'],
        sp_chenxi: ['sp_hankuncheng', 'sp_zhuxinkun', 'sp_renguanyu', 'sp_wangwenxuan', 'sp_liutong', 'sp_chenyaoshi'],
        sp_renguanyu: ['sp_hankuncheng', 'sp_zhuxinkun', 'sp_chenxi', 'sp_wangwenxuan', 'sp_liutong', 'sp_chenyaoshi'],
        sp_wangwenxuan: ['sp_hankuncheng', 'sp_zhuxinkun', 'sp_chenxi', 'sp_renguanyu', 'sp_liutong', 'sp_chenyaoshi'],
        sp_liutong: ['sp_hankuncheng', 'sp_zhuxinkun', 'sp_chenxi', 'sp_renguanyu', 'sp_wangwenxuan', 'sp_chenyaoshi'],
        sp_chenyaoshi: ['sp_hankuncheng', 'sp_zhuxinkun', 'sp_chenxi', 'sp_renguanyu', 'sp_wangwenxuan', 'sp_liutong'],
    },
    translation: {
        "wei": "魏",
        "shu": "蜀",
        "wu": "吴",
        "qun": "群",
        "shen": "神",
        "ye": "野",

        "ligongsha": "理工杀",
        "st316sha": "316杀",
        "sp316sha": "316杀-SP",
        "stligongsha": "理工杀",

        "sp_hankuncheng": "SP汉坤成",
        "sp_zhuxinkun": "SP朱辛坤",
        "sp_chenxi": "SP陈曦",
        "sp_renguanyu": "SP任冠宇",
        "sp_wangwenxuan": "SP王文煊",
        "sp_liutong": "SP刘通",
        "sp_chenyaoshi": "SP陈耀仕",
        "sp_puqian": "SP蒲谦",
        "sp_hankunchengzhuxinkun": "汉坤成&朱辛坤",
        "lgs_puqian": "蒲谦",
        "lgs_liutong": "刘通",
        "lgs_chenyaoshi": "陈耀仕",
        "lgs_hankuncheng": "汉坤成",
        "lgs_chenxi": "陈曦",
        "lgs_wangwenxuan": "王文煊",
        "lgs_zhuxinkun": "朱辛坤",
        "lgs_renguanyu": "任冠宇",

        "lgs_fengzichao": "冯梓超",
        "lgs_wangchenhao": "王宸昊",
        "lgs_gedongjian": "葛东建",
        "lgs_jihantao": "纪汉涛",
        "lgs_liuyichu": "刘奕初",
        "lgs_wangrunshizengdiwen": "王润石&曾镝文",
        "lgs_wangzhaowen": "王昭雯",
        "lgs_zhangjunhao": "张峻豪",
        "lgs_zhangtianyu": "张天宇",
        "lgs_wangyujia": "王郁嘉",
        "lgs_qijunkai": "綦俊凯",
        "lgs_wangsiqi": "王思淇",
        "lgs_yubin": "于斌",
        "lgs_wangyixuan": "王逸轩",
        "lgs_guozichen": "郭子晨",
        "lgs_huxiaoyu": "胡晓雨",
        "lgs_wangqi": "王祺",
        "lgs_liujingyi": "刘敬一",
        "lgs_zhangjiahui": "张嘉慧",
        "lgs_sunqingyue": "孙清玥",
        "lgs_pengyuhong": "彭宇鸿",
        "lgs_sunjiazhi": "孙嘉志",
        "lgs_zhouruiqi": "周瑞麒",
        "lgs_wanghongshuo": "王鸿硕",
        "lgs_yeyueda": "叶跃达",
        "lgs_lixiaoting": "李筱汀",
        "lgs_zhangliao": "谋张辽",
        "lgs_zhangliaox": "新谋张辽",
        "lgs_yuxiaoran": "于筱然",
        "lgs_wanglinjing": "王琳璟",
        "lgs_liyifei": "李易非",
        "lgs_luyeyang": "逯业扬",
        "lgs_qujiaqi": "曲家祺",
        "lgs_qiyue": "齐悦",
        "lgs_guojingjun": "郭晶珺",
        "lgs_wangjiaqi": "王佳齐",
        "lgs_weixinran": "魏欣然",
        "lgs_chenglinuo": "程丽诺",
        "lgs_lizhaofu": "李炤甫",
        "lgs_wangyuan": "王媛",
        "lgs_muqing": "穆青",
        "lgs_wanghuan": "王欢",
        "sp_zengdiwen": "曾镝文",
        "sp_wangrunshi": "王润石",
        "sp_wangyixuan": "SP王逸轩",
        "sp_wanghongshuo": "SP王鸿硕",


        "lgs_gangrou": "刚柔",
        "lgs_gangrou_info": "<b>转换技</b>，阴：你可以将一张非基本牌当【杀】使用或打出，然后重铸一张基本牌。阳：出牌阶段，你可以弃置一张黑色牌，重置本回合【杀】的使用次数。",
        "lgs_yanhuan": "言欢",
        "lgs_yanhuan_info": "当你于回合内使用♦牌、弃置♠牌，或于回合外使用♥牌、弃置♣牌时，可以摸一张牌。",
        "lgs_gangqu": "刚躯",
        "lgs_gangqu_info": "当你需要使用或打出【杀】时，可以展示所有手牌，若其中：有【杀】，你弃置所有【杀】并摸等量的牌，然后视为你使用或打出了一张【杀】；没有【杀】，你可以将一张牌当【杀】使用或打出，然后本回合你不能再发动此技能。",
        "lgs_liepo": "烈魄",
        "lgs_liepo_info": "当你成为一名角色【杀】的目标时，若你没有【闪】，你可以取消之。若如此做，此【杀】结算后，该角色视为对你使用了一张【决斗】。",
        "lgs_xiushen": "修身",
        "lgs_xiushen_info": "<b>主公技</b>，当与你势力相同的其他角色成为【杀】的目标时，其可以交给你一张【杀】，若如此做，你可以交给其一张【闪】。",
        "lgs_qishi": "起事",
        "lgs_qishi_info": "出牌阶段，你可以弃置一名其他角色一张手牌，然后若该角色只有一种花色的手牌或没有手牌，其可以展示手牌并选择一项：1.弃置你等同于其手牌数的牌；2.对你造成X点伤害（X为本回合其他角色因“<b>起事</b>”展示手牌的次数）。",
        "lgs_yange": "言歌",
        "lgs_yange_info": "<b>锁定技</b>，你的判定牌均视为♣。",
        "lgs_yian": "易安",
        "lgs_yian_info": "<b>锁定技</b>，你的回合外，当你的手牌数与体力值变得相等时，若此时没有体力值低于1的角色，终止一切结算，结束当前回合。",
        "lgs_xiaoyi": "晓义",
        "lgs_xiaoyi_info": "<b>觉醒技</b>，准备阶段，若你已发动“<b>易安</b>”的次数不小于你的手牌数，你将手牌数摸至体力上限，然后减1点体力上限，获得技能“<b>盈缩</b>”。",
        "lgs_yingsuo": "盈缩",
        "lgs_yingsuo_info": "当手牌数不大于你的角色成为【杀】的目标时，你可以选择一项：1.交给其一张手牌，然后摸一张牌；2.收回装备区的任意张牌。",
        "lgs_beishan": "备膳",
        "lgs_beishan_info": "结束阶段，若你没有“<b>膳</b>”，你可以摸2张牌，然后可以将任意张手牌置于你的武将牌上，称为“<b>膳</b>”。",
        "lgs_shenghua": "生花",
        "lgs_shenghua_info": "1级：每轮限一次，其他角色的摸牌阶段结束时，你可以移去一张“<b>膳</b>”，令其执行一个由你选择的任意阶段。2级：一名角色的摸牌阶段结束时，你可以移去X张“<b>膳</b>”，令其执行一个由你选择的任意阶段（X为本轮发动“<b>生花</b>”的次数）。",
        "lgs_manfu": "满腹",
        "lgs_manfu_info": "<b>觉醒技</b>，准备阶段，若你拥有四种花色的“<b>膳</b>”，你回复1点体力或摸2张牌，然后减少1点体力上限，升级“<b>生花</b>”。",
        "lgs_boshi": "博识",
        "lgs_boshi_info": "摸牌阶段，你可以改为观看牌堆顶的10张牌，并获得其中一张牌。",
        "lgs_youtu": "忧途",
        "lgs_youtu_info": "结束阶段，若你本回合的失去牌数≥获得牌数，你可以依次执行至多2次以下效果：令一名角色摸1张牌，然后你可以弃置其1张牌。",
        "lgs_xinyou": "心由",
        "lgs_xinyou_info": "出牌阶段开始时，你可以减1点体力上限，视为使用一张基本牌或非延时锦囊牌。若你上个出牌阶段发动过此技能：1.若你本次视为使用了与上次不同的牌，你摸1张牌；2.若你本次不发动此技能，你失去1点体力。",
        "lgs_qingshen": "轻身",
        "lgs_qingshen_info": "<b>限定技</b>，结束阶段，你可以选择一名其他角色，你依次将装备区里的一张牌当【杀】对其使用，直到你的装备区内没有牌或不能再对其使用【杀】，然后你增加等同于以此法造成伤害总数的体力上限。",
        "lgs_jinyi": "近易",
        "lgs_jinyi_info": "每回合限一次，当你获得牌时，你可以将至多等量的牌交给其他角色。",
        "lgs_qiujin": "求谨",
        "lgs_qiujin_info": "当你失去牌时，若你失去牌的数量：小于X，你可以移除一个“<b>谨</b>”标记并摸等同于失去牌数的牌；等于X，你摸X张牌，且本回合不能再发动“<b>求谨</b>”；大于X，你获得“<b>谨</b>”标记至此次失去牌的数量。（X为你的“<b>谨</b>”标记数）",
        "lgs_polu": "破路",
        "lgs_polu_info": "出牌阶段，你可以将一张牌扣置于没有“<b>破</b>”，且与你相邻，或与有“<b>破</b>”的角色相邻的角色的武将牌旁，称为“<b>破</b>”。有“<b>破</b>”的角色防具失效；当你与其他角色计算距离时，无视所有有“<b>破</b>”的角色；你对有“<b>破</b>”的角色使用牌无距离限制。有“<b>破</b>”的角色的回合开始时，其获得“<b>破</b>”。",
        "lgs_juesha": "绝杀",
        "lgs_juesha_info": "当你对距离为1的角色使用【杀】时，若此【杀】的伤害足以使其进入濒死状态，你可以令此【杀】不可被闪避且伤害+1。",
        "lgs_daimeng": "呆萌",
        "lgs_daimeng_info": "当你成为点数大于等于10的牌的目标时，可以令之对你无效。",
        "lgs_shensuan": "神算",
        "lgs_shensuan_info": "<b>转换技</b>，阴：当你使用或打出牌时，可以弃置任意张牌，若这些牌与你使用或打出的牌点数总和等于13，你摸3张牌。阳：当其他角色使用牌指定唯一目标时，你可以弃置其一张牌，若此牌与其使用的牌点数之和大于13，其摸2张牌。",
        "lgs_fengyu": "讽喻",
        "lgs_fengyu_info": "其他角色的结束阶段，若其本回合未造成过伤害，你可以令其弃1张牌。若为第一次对其发动此技能，则改为弃2张牌。",
        "lgs_jianxing": "坚行",
        "lgs_jianxing_info": "出牌阶段开始时，或当你体力值变化时，你可以展示一名角色一张手牌，其下一个结束阶段前，直到其使用此牌或受到伤害，其不能使用或打出此牌以外的其他牌。其使用此牌时若在你的回合，你摸1张牌。",
        "lgs_yonglan": "慵懒",
        "lgs_yonglan_info": "<b>锁定技</b>，你的回合外，当有角色使用牌指定唯一目标，且你需要使用或打出牌响应之时，若你不响应此牌，你摸一张牌；若你响应此牌，响应后你弃一张牌。",
        "lgs_yinzhi": "隐智",
        "lgs_yinzhi_info": "你可以将四张花色各不相同的牌一起当任意基本牌或普通锦囊牌使用，然后回复1点体力。",
        "lgs_guanglan": "广览",
        "lgs_guanglan_info": "有手牌的其他角色的开始阶段，你可以观看其手牌，并选择一项：1.用一张其手牌中不含有的类别的牌交换其中一张牌；2.摸一张牌并受到一点伤害。",
        "lgs_hairong": "海容",
        "lgs_hairong_info": "当你受到伤害后，可以选择一项：1.摸一张牌；2.令当前回合角色摸X张牌，然后本回合你成为其牌的目标时，你可以为此牌减少至多X个目标（X为你手牌中包含的类别数）。",
        "lgs_kubi": "苦逼",
        "lgs_kubi_info": "每回合限一次，当你需要使用或打出某种牌名的牌时，若你手牌中没有此牌名的牌，你可以摸1张牌，若你摸的牌不是此牌名，你翻面。<b>锁定技</b>，若你背面朝上，你的手牌上限+3。",
        "lgs_tiewan": "铁腕",
        "lgs_tiewan_info": "准备阶段，你可以令本回合出牌阶段最多使用一张非装备牌，若如此做，本回合你使用非装备牌指定目标时，可以令其中一名目标不能使用或打出与此牌颜色相同的牌直到回合结束，然后对其造成一点伤害。",
        "lgs_zaoxing": "早行",
        "lgs_zaoxing_info": "每轮限一次，一名角色的回合开始时，你可以摸3张牌。若如此做，跳过你的下个摸牌阶段。出牌阶段，你可以选择一项：1.弃2张牌，令一名其他角色摸1张牌；2.弃1张牌，失去1点体力并摸2张牌。若如此做，本轮你跳过弃牌阶段。",
        "lgs_qianye": "潜夜",
        "lgs_qianye_info": "当你成为其他角色使用牌的唯一目标时，你可以摸一张牌。若如此做，该牌结算结束后，你须弃置1张手牌。",
        "lgs_tianle": "天乐",
        "lgs_tianle_info": "每回合限一次，当你成为其他角色牌的目标时，可以摸1张牌并展示之，然后进行一次判定，若颜色与你展示的牌相同，取消之。",
        "lgs_jieyou": "解忧",
        "lgs_jieyou_info": "其他角色出牌阶段开始时，你可以交给其等同于其体力值的牌，该出牌阶段当其使用了所有因“<b>解忧</b>”获得的牌时，你令其回复一点体力；出牌阶段结束时，若其未使用所有“<b>解忧</b>”牌，你失去一点体力。",
        "lgs_zhiyong": "智勇",
        "lgs_zhiyong_info": "你可以将全部手牌当一张【杀】使用或打出。结算后，若此【杀】造成过伤害，你摸X+1张牌（X为转化为此【杀】的牌数），然后本回合不能再发动“<b>智勇</b>”；若未造成伤害，你获得响应此杀的闪或此杀响应的牌。",
        "lgs_linyi": "凛义",
        "lgs_linyi_info": "<b>限定技</b>，结束阶段，你可以将体力上限减少至1，并令1至X名角色各获得两点护甲（X为减少的体力上限数）。若如此做，你死亡时，全场角色失去所有护甲。",
        "lgs_miaokou": "妙口",
        "lgs_miaokou_info": "当数量大于1的牌进入弃牌堆时，你可以调整其顺序。当你使用或打出牌时，若此牌与弃牌堆顶的牌花色或点数相同，你可以摸1张牌。",
        "lgs_feiqiu": "非酋",
        "lgs_feiqiu_info": "<b>锁定技</b>，当你判定时，若当前判定牌将导致判定失效，你获得判定牌并重新判定。你重复此流程直到判定牌将导致判定生效。",
        "lgs_yeyin": "夜隐",
        "lgs_yeyin_info": "当你受到伤害或成为黑色牌的目标时，若你的手牌中：没有红色牌，你可以摸X张牌；有红色牌，你可以将一张红色手牌交给其他角色，然后弃置其他红色手牌并进行判定：若为红，令此伤害-1/牌对你无效。（X为你受到此牌的伤害）",
        "lgs_qiezhu": "切嘱",
        "lgs_qiezhu_info": "出牌阶段，你可以将一张武器牌交给一名其他角色，并令其获得弃牌堆中的一张【杀】；或将一张【杀】交给一名可成为你【借刀杀人】目标的角色，并视为对其使用一张【借刀杀人】。",
        "lgs_woxun": "我寻",
        "lgs_woxun_info": "<b>使命技</b>，准备阶段和结束阶段，或当你造成或受到伤害时，你将牌堆顶的一张牌置于武将牌上，称为“<b>影</b>”。当你每回合第一次使用或打出牌时，可以用一张牌替换一张“<b>影</b>”。<br><b>· 成功</b>：出牌阶段开始时，若你拥有至少8张“<b>影</b>”，“<b>影</b>”中包含4种花色和3种类别，且“<b>影</b>”中有数量唯一最多的牌名，你记录此牌名，获得此牌名的所有“<b>影</b>”，然后获得技能“<b>定筹</b>”。<br><b>· 失败</b>：出牌阶段开始时，若你有至少12张“<b>影</b>”，且仍未满足成功条件，你计算“<b>影</b>”中数量最多的牌名，弃置手牌中该牌名的牌。",
        "lgs_dingchou": "定筹",
        "lgs_dingchou_info": "<b>锁定技</b>，“<b>我寻</b>”成功时记录的牌名的牌不计入你的手牌上限，结束阶段你从弃牌堆中随机获得一张该牌名的牌。",
        "lgs_jisun": "极损",
        "lgs_jisun_info": "你可以将♠牌当【闪电】使用；出牌阶段，你可以将判定区里的【闪电】移动给其他角色。",
        "lgs_hongqi": "宏器",
        "lgs_hongqi_info": "每轮各限一次，1.其他角色受到值为1的伤害时，其可以交给你一张牌，若如此做，你可以选择一项：令其摸3张牌并将手牌弃置至X张，或令其摸X张牌并将手牌弃置至3张。2.一名角色即将受到值＞1的伤害时，你可以令其摸等同于伤害值的牌，然后此伤害减至1。（X为场上判定区内的牌数）",
        "lgs_hanxiao": "涵笑",
        "lgs_hanxiao_info": "<b>锁定技</b>，你的手牌上限+2X（X为你手牌中♦牌的数量）。当你失去手牌中最后的♦牌时，你回复一点体力。",
        "lgs_chenghuan": "成欢",
        "lgs_chenghuan_info": "出牌阶段限一次，你可以弃置一张牌，选择一名男性角色和一名女性角色，令其各摸一张牌，且直到你的下个出牌阶段，每当其中一方成为牌的目标时，你可以令另一方也成为此牌的目标。",
        "lgs_ganggan": "刚敢",
        "lgs_ganggan_info": "当你成为其他角色锦囊牌的目标时，你可以对其使用一张无视距离的【杀】，若此【杀】造成了伤害，该锦囊牌对你无效。",
        "lgs_xiyan": "戏言",
        "lgs_xiyan_info": "当你想要使用【杀】或非延时锦囊牌指定一名其他角色为唯一目标时，你可以令该角色猜测你手牌中是否有此牌：若有且其猜测没有，你获得其一张牌；若没有且其猜测有，你视为对其使用了此牌；若其猜对，本回合你不能再发动“<b>戏言</b>”。你发动“<b>戏言</b>”不可选择本回合选择过的牌名。",
        "lgs_xingchi": "行迟",
        "lgs_xingchi_info": "<b>锁定技</b>，当你成为牌的目标时，若你不是此牌的唯一目标，你最后进行此牌的结算。",
        "lgs_bushi": "补食",
        "lgs_bushi_info": "每轮限3次，当其他角色使用【杀】或非延时锦囊牌指定唯一目标时，你可以摸一张牌，然后根据本轮你发动“<b>补食</b>”的次数执行：一次:你摸一张牌；两次:你弃一张牌；三次:你成为此牌的目标。",
        "lgs_cangmo": "藏墨",
        "lgs_cangmo_info": "游戏开始时，你摸2张牌并将2张手牌置于武将牌上，称为“<b>墨</b>”。准备阶段和结束阶段，你可以将一张“<b>墨</b>”与牌堆顶的牌交换。当你成为【杀】或锦囊牌的目标时，若你有与此牌同名的“<b>墨</b>”，你移除一张该牌名的“<b>墨</b>”并令此牌对你无效。出牌阶段，你可以移除一张“<b>墨</b>”，将一张牌当作与此“<b>墨</b>”相同的牌使用，然后从牌堆顶补充一张“<b>墨</b>”。",
        "lgs_youli": "游历",
        "lgs_youli_info": "<b>锁定技</b>，出牌阶段结束时，若你拥有技能“<b>藏墨</b>”且你没有“<b>墨</b>”，你观看至多两名角色的手牌，并将其中至多两张类别不同的牌置于武将牌上当作“<b>墨</b>”（每名角色最多选一张）。若你以此法获得的“<b>墨</b>”数小于2，你失去一点体力。",
        "lgs_shanxuan": "闪炫",
        "lgs_shanxuan_info": "摸牌阶段，你可以多摸X张牌(X为你的体力值的最低纪录)。",
        "lgs_jieyi": "解意",
        "lgs_jieyi_info": "每回合限一次，其他角色使用【杀】或锦囊牌时，你可以弃一张牌令此牌无效，然后其摸两张牌。若此牌目标包含该角色自己，你摸两张牌。",
        "lgs_shannian": "善念",
        "lgs_shannian_info": "一名角色因弃置而失去牌后，你将这些牌置入仁库；一名角色因摸牌而获得牌后，你可以将仁库中至多等量的牌置于牌堆顶。",
        "lgs_jingyao": "憬遥",
        "lgs_jingyao_info": "<b>限定技</b>，出牌阶段，你可以弃置X张牌并选择一名其他角色（X为你与其的距离），你与其上家交换位置，然后该角色获得技能“<b>芳许</b>”并获得X个“<b>许</b>”标记。",
        "lgs_fangxu":"芳许",
        "lgs_fangxu_info":"摸牌阶段，若你有“<b>许</b>”标记，你可以选择一项：1.多摸1张牌；2.移除一个“<b>许</b>”标记并多摸2张牌。",
        "lgs_qishang": "绮尚",
        "lgs_qishang_info": "游戏开始时，你获得4个“<b>绮</b>”标记。出牌阶段，你可以摸2张牌，然后若你手牌中包含的花色数：小于X，你移除1个“<b>绮</b>”标记；大于等于X，你随机弃置X张手牌，若你以此法弃置的牌数小于3，你将“<b>绮</b>”标记数量补至4，且本回合不能再发动“<b>绮尚</b>”。（X为“<b>绮</b>”标记数。）",
        "lgs_qiaohui": "巧慧",
        "lgs_qiaohui_info": "当你获得牌后，若你手牌中没有重复花色，你可以摸1张牌。",
        "lgs_qingwei": "清卫",
        "lgs_qingwei_info": "当你受到伤害时，你可以交给伤害来源一张牌；或当你造成伤害时，可以获得受伤角色一张牌。若如此做，伤害来源选择一项：1.令受伤角色回复一点体力；2.获得技能“<b>镜洁</b>”直到你的下一个“回合结束时”。",
        "lgs_jingjie": "镜洁",
        "lgs_jingjie_info": "<b>锁定技</b>，当你失去牌后，你弃置区域里与失去牌同花色的所有牌。出牌阶段结束时，若你的手牌包含至少三种花色，你弃置所有手牌。结束阶段若你没有手牌，你摸一张牌。",
        "lgs_qiaqun": "洽群",
        "lgs_qiaqun_info": "游戏开始时，你将8张<a class=\"card-link-in-line\" id=\"cl1\" onMouseenter=\"onMouseenterCardLink('cl1')\" onMouseleave=\"onMouseleaveCardLink('cl1')\" href=\"/#/cardIntroduction/huanjuyitang\">【欢聚一堂】</a>加入牌堆。当一名角色使用<a class=\"card-link-in-line\" id=\"cl2\" onMouseenter=\"onMouseenterCardLink('cl2')\" onMouseleave=\"onMouseleaveCardLink('cl2')\" href=\"/#/cardIntroduction/huanjuyitang\">【欢聚一堂】</a>指定目标时，你可以令此牌对任意名目标的效果中的“将一张手牌置入结算区”改为“将牌堆顶的一张牌置入结算区”。",
        "lgs_langfang": "朗放",
        "lgs_langfang_info": "<b>锁定技</b>，其他角色使用牌指定多个目标时，你摸一张牌，然后若你不是此牌目标，你成为此牌目标；你使用牌指定多个目标时，须选择至少一名目标角色，这些角色各摸一张牌。",
        "lgs_chengmian": "成眠",
        "lgs_chengmian_info": "准备阶段，你可以摸3张牌并翻面。<b>锁定技</b>，你的武将牌背面朝上时，你跳过出牌和弃牌阶段。",
        "lgs_zhiji": "鸷击",
        "lgs_zhiji_info": "其他角色的准备阶段，你可以对其使用一张无视距离的【杀】。你发动“<b>鸷击</b>”使用的【杀】第奇数次被闪避时你从牌堆中获得一张【杀】，第偶数次造成伤害时你翻面。",
        "lgs_shuanglun": "爽论",
        "lgs_shuanglun_info": "出牌阶段限一次，你可以与一名其他角色拼点，赢者视为对没赢者使用一张【决斗】。",
        "lgs_yanta": "言他",
        "lgs_yanta_info": "你拼点时，可以用一名不参与拼点的角色的一张手牌当作拼点牌。",
        "lgs_yingcun": "影存",
        "lgs_yingcun_info": "准备阶段，你可以选择一名本局未选择过的其他角色，其记录当前体力上限、体力值与手牌数。你死亡时，可以令任意名“<b>影存</b>”选择过的角色将体力上限、体力值与手牌数调整为记录值。",
        "lgs_fangyan": "芳言",
        "lgs_fangyan_info": "<b>锁定技</b>，你在聊天区发布的文字不会被屏蔽。",
        "lgs_ezuo": "恶作",
        "lgs_ezuo_info": "①出牌阶段限2次，你可以将一张手牌置于武将牌上称为“<b>机关</b>”并用此“<b>机关</b>”记录一名未记录的角色（“<b>机关</b>”及记录角色仅对自己可见），或用一张手牌替换一张已有的“<b>机关</b>”。②被记录的角色使用与对应“<b>机关</b>”同名的牌时，你移除该“<b>机关</b>”并选择一项：1.转移此牌的一名目标；2.令此牌无效，你获得此牌。",
        "lgs_tuqiang": "图强",
        "lgs_tuqiang_info": "<b>觉醒技</b>，开始阶段，若你发动“<b>恶作②</b>”的次数大于存活角色数，你将所有“<b>机关</b>”收归手牌并失去“<b>恶作</b>”，增加一点体力上限，回满体力，然后获得技能“<b>克己</b>”。",
        "lgs_keji":"克己",
        "lgs_keji_info":"若你未于出牌阶段内使用或打出过【杀】，你可以跳过弃牌阶段。",
        "lgs_xingxi": "性喜",
        "lgs_xingxi_info": "准备阶段，你可以选择一项：1.失去一点体力，结束阶段回复一点体力；2.回复一点体力，结束阶段失去一点体力。",
        "lgs_bomie": "驳蔑",
        "lgs_bomie_info": "出牌阶段限一次，当你使用【杀】指定一个目标后，你可以根据以下条件执行相应效果：若其体力值：1.大于你，本回合你使用【杀】没有距离限制，且可以多使用X张【杀】；2.等于你，你摸X张牌；3.小于你，其抵消此【杀】需要多出X张【闪】。（X为其体力值）",
        "lgs_zhenji": "镇纪",
        "lgs_zhenji_info": "每回合限一次，当一名角色使用牌指定多个目标时，你可以选择保留其中一个目标，并取消其他所有目标。",
        "lgs_xinxing": "信行",
        "lgs_xinxing_info": "你可以将区域里的随机一张牌当随机一张当前可使用的非装备jingshu牌使用（无次数限制，不能重复使用相同牌，所有牌均被使用过一次后清空已使用牌记录）。若你以此法使用的牌不是手牌，你摸一张牌，且本回合不能再发动“<b>信行</b>”。",
        "lgs_tuxi": "突袭",
        "lgs_tuxi_info": "摸牌阶段摸牌时，你可少摸任意张牌并选择等量其他角色，你获得其一张手牌并与其谋弈：<br>披甲陷阵：其弃置一张牌；<br>断桥奇袭：其获得“<b>惊</b>”标记。<br>若你负，其跳过下一个弃牌阶段。",
        "lgs_huiwei": "麾围",
        "lgs_huiwei_info": "<b>锁定技</b>，其他角色回合开始时，若其有“<b>惊</b>”标记，其弃置“<b>惊</b>”标记并选择一项：1.本回合手牌上限-1，且令你获得“<b>英姿</b>”直至你下一回合结束；2.交给你一张装备牌。",
        "lgs_tuxix": "突袭",
        "lgs_tuxix_info": "摸牌阶段摸牌时，你可以少摸任意张牌并选择等量其他角色，你获得其一张手牌并与其谋弈：<br>披甲陷阵：你的下一个摸牌阶段摸牌数+1；<br>断桥奇袭：其获得“<b>惊</b>”标记。",
        "lgs_yingzi":"英姿",
        "lgs_yingzi_info":"摸牌阶段，你可以多摸一张牌。",
        "lgs_huiweix": "麾围",
        "lgs_huiweix_info": "<b>锁定技</b>，其他角色回合开始时，若其有“<b>惊</b>”标记，其弃置“<b>惊</b>”标记并选择一项：1.弃置2张非装备牌；2.交给你1张装备牌。",
        "lgs_jingshu": "静姝",
        "lgs_jingshu_info": "当你因弃置而失去牌时，你失去X点体力（X为这些牌中有“<b>静姝</b>”标记的牌数），然后你可以获得失去的牌中的任意张没有“<b>静姝</b>”标记的牌，以此法获得的牌获得“<b>静姝</b>”标记。 ",
        "lgs_duyi": "笃毅",
        "lgs_duyi_info": "每回合限一次，出牌阶段或当你受到伤害时，你可以选择一项：1.将一张手牌置于武将牌上称为“<b>毅</b>”，然后摸1张牌；2.获得任意张“<b>毅</b>”。若如此做，若你的“<b>毅</b>”数量等于体力值，你回复1点体力。",
        "lgs_xiaokan": "笑侃",
        "lgs_xiaokan_info": "出牌阶段，你可以弃置一名手牌数不小于你的其他角色一张牌，若如此做，其选择一项：1.摸X张牌并翻面（X为其手牌数且至多为4），然后本回合你不能再发动“<b>笑侃</b>”；2.受到你造成的一点伤害，然后视为对你使用一张【杀】。",
        "lgs_caisi": "才思",
        "lgs_caisi_info": "你可以将【闪电】和【闪】、【火攻】和火【杀】、【桃园结义】和【桃】、【无中生有】和【无懈可击】相互转化使用或打出。",
        "lgs_chijiang": "驰疆",
        "lgs_chijiang_info": "<b>锁定技</b>，当你使用牌指定目标时，你令除你以外的所有目标获得“<b>疆</b>”标记。你与有“<b>疆</b>”标记的角色及其相邻角色计算距离视为1。结束阶段，若你与全场角色距离为1，你失去一点体力或减一点体力上限，获得所有其他角色区域内的各一张牌，然后弃置等同于场上“<b>疆</b>”标记数的牌并移除所有“<b>疆</b>”标记。",
        "lgs_huiyou": "会友",
        "lgs_huiyou_info": "出牌阶段，你可以弃置任意张手牌，若如此做，你选择一名手牌数小于你的角色，其摸等量的牌，然后摸X张牌（X为你与其手牌中都包含的花色数）。",
        "lgs_yinwei": "淫威",
        "lgs_yinwei_info": "当你使用杀指定一个目标时，可以执行以下效果：若你的手牌数大于该角色，本回合其不能使用手牌；若你的体力值大于该角色，此杀对其伤害+1；若你的技能数大于该角色，本回合其非锁定技失效。",
        "lgs_shenhuai": "深怀",
        "lgs_shenhuai_info": "对每名角色限一次。一名角色进入濒死状态时，你可以弃置2张牌或失去1点体力，令其回复1点体力，若如此做，直到你的下个回合结束，你获得技能“<b>耀武</b>”和“<b>扬威</b>”。",
        "lgs_yaowu": "耀武",
        "lgs_yaowu_info": "<b>锁定技</b>，当一名角色使用【杀】对你造成伤害时，若此杀为红色，该角色回复1点体力或摸一张牌。否则你摸一张牌。",
        "lgs_yangwei": "扬威",
        "lgs_yangwei_info": "出牌阶段限一次，你可以摸两张牌并获得“<b>威</b>”标记直到此阶段结束，然后此技能失效直到下个回合的结束阶段。拥有“<b>威</b>”标记的角色出牌阶段可额外使用一张【杀】、使用【杀】无距离限制且无视防具。",
        "lgs_qjinyi": "锦衣",
        "lgs_qjinyi_info": "每回合限一次，当一张装备牌进入你的装备区后，你可以摸X张牌（X为你装备区的牌数）。",
        "lgs_shuangzhi": "爽直",
        "lgs_shuangzhi_info": "每回合限一次，当你成为其他角色非伤害类锦囊牌的目标时，你可以对其造成一点伤害。",
        "lgs_kaizhu": "慨助",
        "lgs_kaizhu_info": "出牌阶段，你可以将装备区或判定区的一张牌移动给其他角色并令其回复一点体力，然后你废除对应区域；其他角色与你计算距离+X（X为你废除的区域数）；其他角色失去因“<b>慨助</b>”进入其区域的牌后，你恢复你的对应区域。",
        "lgs_jiangxin": "匠心",
        "lgs_jiangxin_info": "当你受到伤害后，可以弃置两张牌（不足则全弃，无牌则不弃），然后摸一张牌并展示之。若你以此法弃置与摸的牌：1.有至少两张花色相同，你摸两张牌；2.三张花色相同，你可以再次发动“<b>匠心</b>”。",
        "lgs_mengxu": "梦续",
        "lgs_mengxu_info": "<b>锁定技</b>，你的任意阶段开始前，若你的手牌数小于4，你摸1张牌并跳过此阶段。",
        "lgs_yiying": "义膺",
        "lgs_yiying_info": "每回合限一次，其他角色使用的目标包含自己的红色牌结算后，若其体力值大于你，你可以选择一项：1.弃置其一张牌；2.视为对其使用一张无距离限制的【杀】。背水：弃置两张手牌。",
        "lgs_biluo": "笔落",
        "lgs_biluo_info": "当你的一张基本牌或普通锦囊牌（包括你的判定牌）因使用之外的原因进入弃牌堆时，你可以视为使用一张与此牌相同的牌（不计次数，无距离限制）。",
        "lgs_qinhe": "亲和",
        "lgs_qinhe_info": "出牌阶段限2次，你可以令一名没有“<b>和</b>”标记的角色获得“<b>和</b>”标记。有“<b>和</b>”标记的角色：1.受到伤害时，摸2张牌，且你可以移除其“<b>和</b>”标记；2.造成伤害时，移除“<b>和</b>”标记并弃置2张牌。",
        "lgs_shiyuan": "释怨",
        "lgs_shiyuan_info": "当一名角色使用【杀】指定一个目标时，你可以取消之，该角色收回此【杀】，然后根据你对该角色发动“<b>释怨</b>”的次数执行以下效果：一次，你与其各摸一张牌；两次，其可以对你使用一张【杀】；三次，你失去技能“<b>释怨</b>”。",
        "lgs_qianyin": "千音",
        "lgs_qianyin_info": "<b>锁定技</b>，当你造成伤害、受到伤害或回复体力后，你失去上次因“<b>千音</b>”获得的技能，然后随机获得一个“理工杀”扩展包的技能（不可重复获得相同技能，不可获得觉醒技、使命技和联动技能）。",
        "lgs_jifei": "嫉非",
        "lgs_jifei_info": "其他角色使用牌指定除你和其以外的角色为唯一目标时，你可以与其拼点，赢者摸一张牌并展示之。",
        "lgs_minghao": "明毫",
        "lgs_minghao_info": "其他角色的结束阶段，你可以猜测其手牌中是否有某种牌名的牌。若猜对，你根据牌名执行对应效果，然后可以再次发动“<b>明毫</b>”（不得猜测本回合猜过的牌名）；若一回合内首次即猜错，本轮“<b>明毫</b>”失效。<br><b>·</b> 牌名及对应效果：<br><b>·</b>【杀】：你视为对其使用一张【杀】；<br><b>·</b>【闪】：你弃置其一张牌；<br><b>·</b>【桃】或【酒】：你获得其一张牌；<br><b>·</b> 锦囊牌：其弃置此牌名的所有牌并横置武将牌；<br><b>·</b> 装备牌：你对其造成一点伤害。",
        "lgs_zhiqian": "执前",
        "lgs_zhiqian_info": "<b>锁定技</b>，摸牌阶段，若你的手牌数为全场最少，你改为摸X张牌（X为手牌最多角色手牌数）；弃牌阶段，若你的手牌数为全场最多，你改为弃Y张牌（Y为手牌最少角色手牌数）。",
        "lgs_wendao": "问道",
        "lgs_wendao_info": "当你想要使用牌时（濒死使用【桃】【酒】和使用【无懈可击】时除外），你可以弃2张牌并摸1张牌，或弃1张牌并摸2张牌。若如此做，本次你使用牌时：①使用与弃置的牌同花色的牌无次数与距离限制，②不能使用与摸的牌同类型的牌。",
        "lgs_fengsao": "风骚",
        "lgs_fengsao_info": "每回合限3次，你可以将一张牌当作其他角色使用牌历史记录中的倒数第X张非装备牌使用（X为本回合你发动此技能的次数；以此法使用牌无距离与次数限制）。",
        "lgs_weizun": "唯尊",
        "lgs_weizun_info": "<b>限定技</b>，出牌阶段，你可以选择一名目标，然后令除你以外的所有角色依次执行：其可以对该目标使用一张牌，若其使用了牌，本局游戏你于出牌阶段可使用【杀】的次数+1，若其未使用牌，你可以视为对其使用一张【杀】（不计次数）。",
        "lgs_liangcong": "良从",
        "lgs_liangcong_info": "当你对其他角色造成伤害时，你可以将装备区的一张牌移入该角色的装备区，然后你可以选择一项：1.你摸2张牌；2.该角色回复1点体力。",
        "lgs_gufang": "孤芳",
        "lgs_gufang_info": "结束阶段，你依次执行以下两项：1.若你装备区牌的数量不为全场唯一最多，你可以将场上的一张装备牌移入你的装备区；2.若你装备区牌的数量为全场唯一最多，你可以摸1张牌。",
        "lgs_yasi": "雅思",
        "lgs_yasi_info": "出牌阶段限一次，你可以弃置一张红色牌，令一名角色进行一次判定，若点数不小于7，其摸2张牌并回复1点体力。",
        "lgs_linuo": "立诺",
        "lgs_linuo_info": "每回合限一次，一名角色的判定牌生效前，你可以亮出牌堆顶的一张牌，并对判定牌执行以下更改之一：1.点数+X；2.点数-X；3.花色改为亮出牌的花色。（牌面永久更改，X为亮出牌的点数。）执行结束后，你将亮出的牌置入弃牌堆。",
        "lgs_huishi": "慧识",
        "lgs_huishi_info": "对每名其他角色限一次。其他角色的结束阶段，你可以猜测其身份（你的猜测仅该角色可知），其须告知你是否正确。若猜测正确，其获得“<b>识</b>”标记；若猜测不正确，你可以对其造成一点伤害，然后“<b>慧识</b>”失效直到你的下回合开始。",
        "lgs_jiechong": "节冲",
        "lgs_jiechong_info": "<b>觉醒技</b>，准备阶段，若你对所有当前存活的其他角色发动过“<b>慧识</b>”，你减一点体力上限，获得技能“<b>忘嫌</b>”，然后令有“<b>识</b>”标记的角色依次选择一项：1.移除“<b>识</b>”标记，然后受到你造成的3点伤害；2.亮出身份牌，然后你可以视为对其使用一张【杀】。",
        "lgs_wangxian": "忘嫌",
        "lgs_wangxian_info": "当有“<b>识</b>”标记的角色对你造成伤害时，你可以令其摸3张牌；当你对有“<b>识</b>”标记的角色造成伤害时，你可以摸3张牌，然后你本回合使用牌不能再指定该角色为目标。",
        "lgs_chaojie": "嘲解",
        "lgs_chaojie_info": "当你受到伤害时，你可以令你与伤害来源中手牌较多者将手牌弃置至数量与对方相同，若伤害来源未以此法弃置牌，此伤害对你无效。",
        "lgs_jueyi": "决意",
        "lgs_jueyi_info": "当一名角色使用【杀】指定一个目标时，你可以弃置一张牌，令目标角色不能使用【闪】。",
        "lgs_qinmian": "勤勉",
        "lgs_qinmian_info": "当你于回合内使用牌时，若你有可弃置的牌，你可以弃置X张牌（不足则全弃）并摸X张牌（X为本回合发动“<b>勤勉</b>”的次数）。若你以此法弃置了所有牌，则你增加1点体力上限（最多加至5），然后本回合不能再发动“<b>勤勉</b>”。",
        "lgs_yunshi": "蕴诗",
        "lgs_yunshi_info": "出牌阶段限一次，若你手牌中的花色数等于体力值，你可以回复1点体力。",
        "lgs_jiaoxin": "交心",
        "lgs_jiaoxin_info": "出牌阶段对每名角色限一次，你可以与一名其他角色各选择一张手牌并交换。若你选择的是♥牌：1.若其选择的也是♥牌，你可以令其摸1张牌；2.若其选择的不是♥牌，你可以令其失去1点体力。",
        "lgs_keyan": "恪严",
        "lgs_keyan_info": "<b>锁定技</b>，结束阶段，你摸3张牌，然后弃置一种颜色的所有手牌。",
        "lgs_renjian": "韧坚",
        "lgs_renjian_info": "当你于一回合内受到第2点伤害时，你可以回复1点体力。",
        "lgs_zhanyue": "展跃",
        "lgs_zhanyue_info": "你可以视为使用【杀】。<b>锁定技</b>，当你使用的虚拟【杀】结算后，若没有【闪】响应此【杀】，你失去1点体力并摸等同于已失去体力值数量的牌，然后本回合使用实体非转化【杀】无次数与距离限制。",
        "lgs_huixie": "诙谐",
        "lgs_huixie_info": "你使用♦基本或普通锦囊牌可以多指定一个目标；其他角色使用♦基本或普通锦囊牌可以指定你为额外目标。",
        "lgs_jieshen": "洁身",
        "lgs_jieshen_info": "当你受到伤害时，你可以弃置所有手牌，然后若你弃置的牌数：小于3，你摸3张牌，令此伤害的值最多为1；大于等于3，你摸2张牌，然后回复一点体力。",
        "lgs_fenqu": "奋取",
        "lgs_fenqu_info": "当你使用【杀】指定一个目标时，若此【杀】有点数，可以令该角色交给你任意张总点数>X的牌（X为此【杀】的点数，若其所有牌的总点数≤X则全部交出）。若其交出的牌总点数>10，此【杀】对其无效。",
        "lgs_zongyu": "纵欲",
        "lgs_zongyu_info": "摸牌阶段摸牌时，你可以选择一项：1.回复一点体力，少摸一张牌；2.失去一点体力，多摸两张牌。",
        "lgs_nixi": "逆袭",
        "lgs_nixi_info": "当你回复体力时，你可以视为使用一张【杀】（无距离与次数限制），当此【杀】：造成伤害时，你摸一张牌；被闪避时，你失去一点体力。",
        "lgs_zhenmi": "缜密",
        "lgs_zhenmi_info": "当你使用或打出牌后，你可以摸一张牌，然后弃一张牌。若你弃置的牌为装备牌，本回合你不能再发动“<b>缜密</b>”，然后你可以将至多3张本回合因“<b>缜密</b>”弃置且仍在弃牌堆中的牌交给一名其他角色，",
        "lgs_jiehuo": "解惑",
        "lgs_jiehuo_info": "当你攻击范围内的其他角色需要使用或打出【闪】时，其可以令你选择是否将一张非装备牌当做【闪】替其使用或打出。当你以此法使用或打出转化【闪】时，若对应的实体牌不是【闪】，你失去一点体力。",
        "lgs_shouye": "授业",
        "lgs_shouye_info": "其他角色的准备阶段，你可以展示一张非装备手牌，本回合其可以将一张牌当做你展示的牌使用（限一次）。若如此做，本回合结束阶段，若其本回合因“<b>授业</b>”使用过牌，其获得你展示的牌并摸2张牌。",
        "lgs_ciai": "慈爱",
        "lgs_ciai_info": "<b>锁定技</b>，你不能使用♠非装备牌或成为♠非装备牌的目标；你使用♥牌时，此牌除造成伤害以外的效果值+1。",
        "lgs_shixin": "师心",
        "lgs_shixin_info": "<b>主公技</b>，当一名与你同势力的其他角色从你的区域里获得牌时，若其手牌数不小于你，你可以令其摸1张牌。",
        "lgs_touliang": "偷梁",
        "lgs_touliang_info": "<b>锁定技</b>，当一名其他角色跳过任意阶段时，或一名其他角色出牌阶段结束后，若该出牌阶段其未使用牌指定过除其以外的角色为目标，你摸一张牌并执行一个额外的此阶段。",
        "lgs_huanzhu": "换柱",
        "lgs_huanzhu_info": "其他角色的回合开始前，若你正面朝上，你可以减一点体力上限，与其交换位置并摸x张牌(x为你与其位次之差) ，然后将此回合改为你的回合。若如此做，本回合结束后，你将武将牌翻面，然后将手牌数调整至体力上限。",
        "lgs_zhenghuo": "整活",
        "lgs_zhenghuo_info": "每当你造成一点伤害后（改：使用非延时锦囊牌或【杀】时），你获得一个“<b>活</b>”标记。当你即将受到值＞1的伤害时，你可以弃置一个“<b>活</b>”标记，令此伤害-1（改：防止此伤害）。",
        "lgs_huahuo": "花活",
        "lgs_huahuo_info": "<b>觉醒技</b>，准备阶段，若你的“<b>活</b>”标记数≥3，你减一点体力上限，修改技能“<b>整活</b>”并获得技能“<b>狠活</b>”。",
        "lgs_henhuo": "狠活",
        "lgs_henhuo_info": "当你造成伤害时，你可以弃置至少2个“<b>活</b>”标记并进行X次判定（X为弃置的“<b>活</b>”标记数-1），然后可以执行以下选项中的至多Y项（Y为判定结果为黑色的次数）：1.重置本回合【杀】的使用次数；2.获得所有黑色判定牌；3.弃置一张牌令此伤害+1。",

        "huanjuyitang": "欢聚一堂",
        "huanjuyitang_info": "出牌阶段，对所有角色使用。你选择一项，令所有目标依次执行：1.弃一张牌，然后摸一张牌，若其上下家手牌数相等则多摸一张牌；2.摸一张牌，然后弃一张牌，若其上下家手牌数相等则多弃一张牌。",
    },
}